### ISSUE TITLE
Missed IRQs at the end of each quantum (?)

### ISSUE THREAD

**Issue by Robeast** [janweinstock/vcml#8]
I've had trouble with VCML as used in AVP. After bisecting the problem (thx to @Lukas Juenger) I've found out that the following commit breaks the correct functionality:

https://github.com/janweinstock/vcml/commit/e26c855d105aba467d09d0eae8537282e7c2b572?diff=unified

(If I add the two removed lines, everything works fine.)

The symptoms are difficult to describe. After Linux boot, sometimes I can't get into the console. Sometime I get in but when executing e.g. "ls -la" or so, the output comes discretely in a couple of seconds difference or only by pressing a key multiple times. Once a kernel panic happened arising from the IRQ handler.

Our wild guess: MMIO interrupts are frequently missed somehow at the end of the quantum. 

Would you happen to know why this happens? Could you suggest a fix please?

**Comment by janweinstock** [comment]
Hi Rob,

I am not quite sure what the reason for this behaviour is, since I don't have access to AVP. However, to restore the old behaviour it might be sufficient to just call `sync()` in your `b_transport` callback before you access the sockets.

To find the true reason for this behaviour it might be necessary to figure out which component is responsible for stalling the interrupts (i.e. gic or uart) and why this happens. Technically none of these models should rely on syncing twice for every mmio access (and in any case, since the local time offset is normally zero, `sync()` should not change timing behaviour).

**Comment by Robeast** [comment]
Hi Jan,

we figured out the issue with Lucas. The solution was to add an extra wait(SC_ZERO_TIME) in greensocs -> tlm2c_bridge.cpp in the do_io(...) function after send(...). The problem was that when the CPU does an MMIO call to write any GIC registers for example, there needs to be an extra wait(SC_ZERO_TIME) afterwards so that the notified IRQ event is executed (e.g. setting the IRQ line to 0/1)  and so that this is immediately visible to the CPU before the execution of the next quantum. Else the acknowledgement happens too late.

Since this is not a fault in VMCL, I will now remove the issue. Thanks for your patience :)
